<?php

return [
    'definitions' => [
        [
            'slug' => 'first_task_completed',
            'title' => 'First Win',
            'description' => 'Complete your first task.',
            'condition_type' => 'count',
            'metric_key' => 'completed_tasks',
            'threshold' => 1,
            'badge_icon' => '🌱',
        ],
        [
            'slug' => 'tasks_5_completed',
            'title' => 'Momentum Builder',
            'description' => 'Complete 5 tasks.',
            'condition_type' => 'count',
            'metric_key' => 'completed_tasks',
            'threshold' => 5,
            'badge_icon' => '✅',
        ],
        [
            'slug' => 'tasks_10_completed',
            'title' => 'Task Finisher 10',
            'description' => 'Complete 10 tasks.',
            'condition_type' => 'count',
            'metric_key' => 'completed_tasks',
            'threshold' => 10,
            'badge_icon' => '🏅',
        ],
        [
            'slug' => 'tasks_25_completed',
            'title' => 'Task Finisher 25',
            'description' => 'Complete 25 tasks.',
            'condition_type' => 'count',
            'metric_key' => 'completed_tasks',
            'threshold' => 25,
            'badge_icon' => '🥉',
        ],
        [
            'slug' => 'tasks_50_completed',
            'title' => 'Task Finisher 50',
            'description' => 'Complete 50 tasks.',
            'condition_type' => 'count',
            'metric_key' => 'completed_tasks',
            'threshold' => 50,
            'badge_icon' => '🥈',
        ],
        [
            'slug' => 'tasks_100_completed',
            'title' => 'Task Finisher 100',
            'description' => 'Complete 100 tasks.',
            'condition_type' => 'count',
            'metric_key' => 'completed_tasks',
            'threshold' => 100,
            'badge_icon' => '🥇',
        ],
        [
            'slug' => 'streak_3_days',
            'title' => '3-Day Spark',
            'description' => 'Maintain a 3-day completion streak.',
            'condition_type' => 'streak',
            'metric_key' => 'daily_streak',
            'threshold' => 3,
            'badge_icon' => '🔥',
        ],
        [
            'slug' => 'streak_7_days',
            'title' => '7-Day Flame',
            'description' => 'Maintain a 7-day completion streak.',
            'condition_type' => 'streak',
            'metric_key' => 'daily_streak',
            'threshold' => 7,
            'badge_icon' => '🔥',
        ],
        [
            'slug' => 'streak_14_days',
            'title' => '14-Day Rhythm',
            'description' => 'Maintain a 14-day completion streak.',
            'condition_type' => 'streak',
            'metric_key' => 'daily_streak',
            'threshold' => 14,
            'badge_icon' => '⚡',
        ],
        [
            'slug' => 'streak_30_days',
            'title' => '30-Day Legend',
            'description' => 'Maintain a 30-day completion streak.',
            'condition_type' => 'streak',
            'metric_key' => 'daily_streak',
            'threshold' => 30,
            'badge_icon' => '⭐',
        ],
        [
            'slug' => 'all_tasks_in_day_once',
            'title' => 'Perfect Day',
            'description' => 'Complete all tasks created in a single day.',
            'condition_type' => 'behavior',
            'metric_key' => 'perfect_days',
            'threshold' => 1,
            'badge_icon' => '📅',
        ],
        [
            'slug' => 'all_tasks_in_day_5_times',
            'title' => 'Perfect Weekdays',
            'description' => 'Achieve 5 perfect task days.',
            'condition_type' => 'behavior',
            'metric_key' => 'perfect_days',
            'threshold' => 5,
            'badge_icon' => '🗓️',
        ],
        [
            'slug' => 'no_overdue_week',
            'title' => 'Clean Week',
            'description' => 'Keep zero overdue tasks for 7 consecutive days.',
            'condition_type' => 'behavior',
            'metric_key' => 'overdue_free_streak',
            'threshold' => 7,
            'badge_icon' => '🛡️',
        ],
        [
            'slug' => 'no_overdue_month',
            'title' => 'Clean Month',
            'description' => 'Keep zero overdue tasks for 30 consecutive days.',
            'condition_type' => 'behavior',
            'metric_key' => 'overdue_free_streak',
            'threshold' => 30,
            'badge_icon' => '🧼',
        ],
        [
            'slug' => 'use_recurring_task_once',
            'title' => 'Automator',
            'description' => 'Create your first recurring task.',
            'condition_type' => 'behavior',
            'metric_key' => 'recurring_tasks_created',
            'threshold' => 1,
            'badge_icon' => '🔁',
        ],
        [
            'slug' => 'use_recurring_task_10',
            'title' => 'Recurring Pro',
            'description' => 'Create 10 recurring tasks.',
            'condition_type' => 'count',
            'metric_key' => 'recurring_tasks_created',
            'threshold' => 10,
            'badge_icon' => '♻️',
        ],
        [
            'slug' => 'high_priority_5_completed',
            'title' => 'High Priority Hero',
            'description' => 'Complete 5 high-priority tasks.',
            'condition_type' => 'count',
            'metric_key' => 'high_priority_completed',
            'threshold' => 5,
            'badge_icon' => '🚨',
        ],
        [
            'slug' => 'high_priority_25_completed',
            'title' => 'Critical Closer',
            'description' => 'Complete 25 high-priority tasks.',
            'condition_type' => 'count',
            'metric_key' => 'high_priority_completed',
            'threshold' => 25,
            'badge_icon' => '🎯',
        ],
        [
            'slug' => 'subtasks_10_completed',
            'title' => 'Detail Oriented',
            'description' => 'Complete 10 subtasks.',
            'condition_type' => 'count',
            'metric_key' => 'completed_subtasks',
            'threshold' => 10,
            'badge_icon' => '🧩',
        ],
        [
            'slug' => 'due_date_20_completed',
            'title' => 'Deadline Keeper',
            'description' => 'Complete 20 tasks that had due dates.',
            'condition_type' => 'count',
            'metric_key' => 'due_date_tasks_completed',
            'threshold' => 20,
            'badge_icon' => '⏳',
        ],
    ],
];
